### PR TITLE
IntercomService for direct and group communication

### PR DESCRIPTION
**Pull request by n0rthin**
There were a lot of discussions on communication between assistants. I wanted to go ahead and implement something simple that works but could be extended into something complex. This pull request includes the implementation of direct and group communication.

Here's what this PR introduces to the repo:
1. Extended assistant instructions that include communication guideline
2. Chat tools for function calling
3. Agent class that stores information on agent, handles thread runs, processes function calls
4. Agent registry for keeping links to all agents in one place
5. InterComService class - passes messages between agents
6. [Two demos showing how it works ](https://github.com/n0rthin/OpenAI_Agent_Swarm/blob/intercom/intercom/README.md#running-a-demo)

For more details, check out [README.md](https://github.com/n0rthin/OpenAI_Agent_Swarm/blob/intercom/intercom/README.md)

### CODE REVIEW

**Comment by guillermo-delrio** [comment]
This looks very interesting. Haven't had a chance to go through the code in detail yet, however I think it looks similar to my tests over at _agents/agent_funtions_.
Would you mind taking a look at the readme there? Maybe there's an insight that could be of use here.

**Comment by daveshap** [comment]
Waiting for @guillermo-delrio and @OWigginsHay to bless this. Thanks for jumping in.

**Comment by OWigginsHay** [comment]
Looks like a good start, I am also yet to test the actual code! I will try to do so tonight, and if it looks good I will mark my approval on this

**Comment by UrbanLegendXV** [comment]
I'm poking at it now.

**Comment by daveshap** [comment]
Awaiting final approval @OWigginsHay @RomanGoEmpire @GeorgiaPhillips1008 @guillermo-delrio

**Comment by guillermo-delrio** [comment]
I've finally had a chance to look into this in more detail. It is extermely similar to what we've been working on for the manual assistant tests. I'm afraid we would be duplicating the functionality if we merge this as is.
@n0rthin how do you feel about bringing some of these functionalitites directly into _agents/manual_assistants_? I think that might be the best way to keep the project tidy.

Specifically I'd be keen to get:
- Logging per agent (I was about to implement this myself)
- Communication with AgentBuilder and ToolMaker
- Dynamic channels

Let me know if you agree and we can close this PR.

**Comment by n0rthin** [comment]
Hi, @guillermo-delrio. Thanks for the feedback. If merging this PR will lead to duplication of functionality, then I agree that it's better not to merge it. 
I'll look into _agents/manual_assistants_ later to see what I can do.

Have a nice day!

**Pull request closed without merging**
