### PR TITLE
Proposal for Repository Restructuring V1.1

### PR DESCRIPTION
**Pull request by RomanGoEmpire**
Here is the revised restructuring, now incorporating the recent modifications made by the toolmaker. I didn't handle many forks and pull requests before, which led to some mistakes. This represents the updated iteration of #79.

### CODE REVIEW

**Comment by arcovaa** [comment]
oh dang, we're moving pretty fast, tool maker already with a PR and merged? crazy dude

**Comment by RomanGoEmpire** [comment]
@OWigginsHay is tool_demo.py (the file was in root before) still needed ?

**Comment by OWigginsHay** [comment]
Hi @RomanGoEmpire not it is not. Also a previous PR from someone removed an important folder. I have a hotfix on my branch which is synced with the current main in the repo. Go ahead and force PR as needed and after todays PRs are closed, I will apply the hotfix for tools

**Comment by OWigginsHay** [comment]
@RomanGoEmpire unless this PR is still a work in progress, at which point I will apply my hotfix now so up-to-date forkers can run the code error free

**Comment by RomanGoEmpire** [comment]
> @RomanGoEmpire unless this PR is still a work in progress, at which point I will apply my hotfix now so up-to-date forkers can run the code error free

From my side it is done. I would like to standardize the structure of each agent but the "problem" is that the whole code of Agent builder is centered around the file structure it currently has. I think to edit tool-maker structure is way easier (move all files into a folder that dont have a main() function

**Comment by RomanGoEmpire** [comment]
@OWigginsHay If you are okay with the current state you can merge it.

**Comment by OWigginsHay** [comment]
> @OWigginsHay If you are okay with the current state you can merge it.

You are referring to this PR or my hotfix. I'm assuming you mean you are done with this but I want to double check

**Comment by OWigginsHay** [comment]
IMO getting decent project structure is going to be important, especially while the other PRs are small and conflict won't be too bad! So I want to get this in ASAP

**Comment by RomanGoEmpire** [comment]
please update the current main branch with your hotfix. I will update my PR then

**Comment by OWigginsHay** [comment]
Marged. You can fix the conflict and I will merge this.

**Comment by RomanGoEmpire** [comment]
should be the code_of_conduct.md in documentation or in root?

**Comment by OWigginsHay** [comment]
I would say code of conduct should be root, along with the main README which seems to be missing? The one that appears at the front of the github page

**Comment by RomanGoEmpire** [comment]
> I would say code of conduct should be root, along with the main README which seems to be missing? The one that appears at the front of the github page

image

The README is in Root

**Comment by RomanGoEmpire** [comment]
Also I am not sure why it still says that there are conflicts. chat_manager is the same

**Comment by OWigginsHay** [comment]
Sorry, I was reading the commit diff.

**Comment by RomanGoEmpire** [comment]
It should be up to date now. With the current main branch and your hotfix

**Comment by OWigginsHay** [comment]
Looks good, I just can't tell why there is still a conflict with that file

**Comment by RomanGoEmpire** [comment]
I moved the imports around(because of my formatter).The conflict was already before. Can you try to resolve it with the button here on github?

**Comment by RomanGoEmpire** [comment]
Now it is done. I understood how to merge the incoming changes 😅

**Pull request merged**
