### PR TITLE
Colorful chats, .env for api key, .gitignore updated, and python requirements.txt

### PR DESCRIPTION
**Pull request by soul-filament**
Just some Qol stuff since i want to get deeper into this.     

Example of how chats now look:

Screenshot 2023-11-10 at 1 57 13 PM

### CODE REVIEW

**Review by soroshsabz — APPROVED** [review]

**Comment by daveshap** [comment]
This is putting a lot of stuff in the root of the repo. Please move it to the correct subfolders and resubmit.

**Comment by gruckion** [comment]
Have you used poetry before? I use it on production projects, very nice tool.

https://python-poetry.org/docs/basic-usage/#project-setup

**Comment by daveshap** [comment]
Please update the scope of this PR or it will be closed soon. We need to reduce noise.

**Comment by daveshap** [comment]
PR still has conflicts. Will close tomorrow if it is not updated.

**Pull request closed without merging**
